### ISSUE TITLE
seeing utils.isGlob error with versions of micromatch > 2.3.1

### ISSUE THREAD

**Issue by bcoe** [jonschlinkert/micromatch#52]
Note, this error does not occur with `2.1.6`, but has occurred since `2.3.1`:

```sh
TypeError: lazy-cache utils.isGlob is not a function /Users/benjamincoe/bcoe/nyc/node_modules/micromatch/node_modules/lazy-cache/index.js
    at matcher (/Users/benjamincoe/bcoe/nyc/node_modules/micromatch/index.js:301:14)
    at Function.any (/Users/benjamincoe/bcoe/nyc/node_modules/micromatch/index.js:239:19)
    at NYC.shouldInstrumentFile (/Users/benjamincoe/bcoe/nyc/index.js:136:25)
    at NYC.addFile (/Users/benjamincoe/bcoe/nyc/index.js:98:25)
    at Object.defaultHook (/Users/benjamincoe/bcoe/nyc/index.js:163:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.getter (/Users/benjamincoe/bcoe/nyc/node_modules/micromatch/node_modules/lazy-cache/index.js:32:31)
```

**Comment by doowb** [comment]
@bcoe do you have a script that reproduces this? I pulled down `nyc` and tried running the tests on the `improve-exclude` branch with the latest `micromatch` and all the tests pass.

**Comment by jonschlinkert** [comment]
hmm, I just pulled down and wasn't able to reproduce either. 

<img width="450" alt="screen shot 2015-12-08 at 1 38 00 pm" src="https://cloud.githubusercontent.com/assets/383994/11664663/fa14aef8-9db0-11e5-8c71-b20cdee6d13f.png">

@bcoe / @doowb what version of npm are you on? I'm using latest

**Comment by es128** [comment]
I tried with node v0.12.7 & npm v2.11.3. Tests pass on the `improve-exclude` branch both before and after installing `micromatch@latest`.

However, I *was* able to reproduce similar errors by forcing lazy-cache down to 0.2.1. Not that npm should allow that to happen, but I'm guessing somehow it did.

Suggest publishing lazy-cache as 1.0.0 and using bumping the version here to prevent the possibility.

**Comment by bcoe** [comment]
@jonschlinkert It's weird, tests pass when I install latest, but when I:

`npm link` inside nyc.

and then

`npm link nyc` inside one of the libraries I'm instrumenting, I get this `isGlob` error.

**Comment by bcoe** [comment]
It's interesting, when I traverse into the `node_modules/micromatch` folder post install, the plugin infrastructure seems to not be working great for me:

```sh
micromatch@2.3.5 node_modules/micromatch
├── filename-regex@2.0.0
├── is-extglob@1.0.0
├── array-unique@0.2.1
├── normalize-path@2.0.1
├── is-glob@2.0.1
├── expand-brackets@0.1.4
├── arr-diff@2.0.0 (arr-flatten@1.0.1)
├── regex-cache@0.4.2 (is-primitive@2.0.0, is-equal-shallow@0.1.3)
├── kind-of@3.0.2 (is-buffer@1.1.0)
├── parse-glob@3.0.4 (is-dotfile@1.0.2, glob-base@0.3.0)
├── object.omit@2.0.0 (is-extendable@0.1.1, for-own@0.1.3)
├── extglob@0.3.1 (success-symbol@0.1.0, ansi-green@0.1.1)
└── braces@1.8.2 (repeat-element@1.1.2, preserve@0.2.0, expand-range@1.8.1)
```

```sh
Benjamins-MacBook-Pro:micromatch benjamincoe$ node
> require('./lib/utils.js')
{ [Function]
  filename: [Function: filename],
  isPath: [Function: isPath],
  hasPath: [Function: hasPath],
  matchPath: [Function: matchPath],
  hasFilename: [Function: hasFilename],
  arrayify: [Function: arrayify],
  unixify: [Function: unixify],
  escapePath: [Function: escapePath],
  unescapeGlob: [Function: unescapeGlob],
  escapeRe: [Function: escapeRe] }```

**Comment by jonschlinkert** [comment]
> npm link nyc inside one of the libraries I'm instrumenting, I get this isGlob error.

Hmm, I'll keep digging into it. any more info would be great. 

I'm not sure if this is related yet, but we're getting a similar error for a different lib with the latest npm, but it doesn't use lazy-cache. 

> Suggest publishing lazy-cache as 1.0.0 and bumping the version here to prevent the possibility.

not a bad idea. I have a bunch of linting changes to push up (from switching to eslint). I'll do that at the same time since it should just be a patch

**Comment by doowb** [comment]
@bcoe I just had an issue with "missing modules" and there was a fix published in `npm@3.5.2` (which is the latest.

Another thing to look at is, lazy-cache defers "requiring" modules until they're used. The modules are added as non-enumerable "getters" so the above code is only showing the utils functions that were manually added in `micromatch`. If you do this in the node repl you should see `[Function]`:

```js
var utils = require('./lib/utils.js');
utils.isGlob
```

If you get the error, it could be due to the "missing modules" issue in npm.

Another thought that I had was that `nyc` is wrapping the `require` functionality and since `lazy-cache` is deferring calling `require`, could this wrapping cause the exported function from `is-glob` to be modified?

**Comment by bcoe** [comment]
@jonschlinkert if you: 

1. clone `nyc` and `yargs`.
2. inside `nyc` install the latest tag of micromatch.
3. inside `nyc`, `npm link`.
4. inside `yargs`, `npm link yargs`.
5. inside `yargs` run `npm test` you should get an exception.

**Comment by bcoe** [comment]
@doowb that would make sense, I didn't realize that `lazy-cache` was overriding the require hook -- was this added in the `lazy-cache` post `2.1.6` of `micromatch`?

**Comment by doowb** [comment]
It's not overriding a require hook. It's just creating a "getter" that calls `require` later.

**Comment by jonschlinkert** [comment]
@bcoe we're still trying to figure this out. in the meantime let us know if you have any suggestions or think there is something on our side we can do to fix this. 

@doowb I made properties enumerable in 0.2.5 of lazy-cache. 

Also, fwiw lazy-cache is really doing the equivalent of:

```js
function lazy(name) {
  return function() {
    return require(name);
  };
}
```
But instead of returning functions lazy-cache returns getters to make the syntax nicer to work with. e.g. `foo.bar` instead of `foo().bar`

**Comment by doowb** [comment]
@bcoe I can confirm that I get that error when following the instructions above.

When I do the following from `yargs`, `micromatch` works fine though:

![image](https://cloud.githubusercontent.com/assets/995160/11671100/d3aab2bc-9dd3-11e5-8975-8f430d915b36.png)

From digging in a little more:

 - `micromatch` is using `lazy-cache` to defer requiring modules until they're used.
 - `nyc` adds a require hook in `_wrapRequire`, which checks each required module to see if it should be instrumented.
 - the `shouldInstrumentFile` method that does the checking is using `micromatch.any` but it's causing the checks to run against `micromatch` dependencies because they haven't been required yet.

I'm not exactly sure where to go from here.

**Comment by jonschlinkert** [comment]
> I'm not exactly sure where to go from here.

we can expose an option/method/property on lazy-cache to immediately `require` ("unlazy") all of dependencies.  then we would expose that as an option in consuming libraries like micromatch when it makes sense (like `{cache: false}` or something)

thoughts?

**Comment by bcoe** [comment]
@jonschlinkert I like this idea, and wow you moved fast looking at the commits now -- I'll test the option now.

**Comment by bcoe** [comment]
@jonschlinkert @doowb I've confirmed that the `unlazy` option works :+1: great work.

**Comment by jonschlinkert** [comment]
great! we'll get a patch up asap

**Comment by doowb** [comment]
@bcoe See PR #54 

This adds an `.unlazy` method so you can update [this line](https://github.com/bcoe/nyc/blob/improve-exclude/index.js#L5) in `nyc` to `var micromatch = require('micromatch').unlazy()` and all the dependencies will be required immediately.

**Comment by jonschlinkert** [comment]
@bcoe, we've spent a lot of time discussing this and I'd like to propose that we implement a "kill switch" in lazy cache that forces all dependencies to be required immediately when `process.env.UNLAZY = true` is defined. 

I'm not a big fan of hanging a property off of `process.env`, but this seems like a good use case as it ensures that it will always work, regardless of what implementors decided to expose, and (so far) the only issues we've had seem related to dev (non-production) stuff. Of the three issues reported to date, two were related to transpiling with webpack, and this one. (also fwiw, both webpack issues were related to problems that - to my knowledge - were solved in earlier versions of lazy-cache).

Does this sound ok to you?

**Comment by jonschlinkert** [comment]
here is the code I described above: https://github.com/jonschlinkert/lazy-cache/blob/0.2.7/index.js#L24-L27

**Comment by bcoe** [comment]
@jonschlinkert I have no objection to this, but I'm happy to use the `option` inside of `nyc` itself -- one thing we do in `nyc` which might be worth copying, we prefix the environment variables we pass around:

e.g., `process.env.NYC_CWD`, it might be worth copying this conventions.

**Comment by jonschlinkert** [comment]
> it might be worth copying this convention.

good idea, I've not published code with environment variables before, that's good advice. thx

> I'm happy to use the option inside of nyc itself

We'll keep the option as well. I should have mentioned that the branch I linked to is back-versioned to 0.2.7 since we're considering making a patch to allow earlier versions to use the environmental variable patch if necessary. 

That said, the other reason I'm in favor of the environmental variable is that it is immediate in effect "globally", whereas an option might not be enabled until after it's already too late. In some uses cases like yours it seems like the option might work out okay, but I'd rather be on the safe side now that we have a solution that should work in all cases.

we'll get that environmental variable prefixed, then I'll review with @doowb in the morning.  thanks for the feedback

**Comment by doowb** [comment]
We've allowed dynamic "namespacing" in other modules. This might be a good idea with `lazy-cache` to allow setting the prefix of the environment variable. This will allow more granular control over the "kill switch" and users of libraries will be able to turn off lazy caching just for that library through an environment variable like `process.env.MICROMATCH_UNLAZY`.

We can still have a global setting like `process.env.LAZY_CACHE_UNLAZY`.

I like the environment variable approach because it reduces the amount of boilerplate/wrapping code that's required in libraries (like this one) that use lazy-cache.

**Comment by jonschlinkert** [comment]
hmm, interesting. my first reaction was that it would be overkill. but I can see how that could be pretty useful. 

> because it reduces the amount of boilerplate/wrapping code that's required in libraries (like this one) that use lazy-cache.

agreed. it doesn't need any now and I'd start ripping it out of everything if it did. Hopefully it doesn't come to that, the performance benefits are worth a bit of a battle, but there are limits :)

**Comment by es128** [comment]
Regardless of all these improvements being planned, seems like in this particular case that is-glob is so likely to be used with any invocation of micromatch that it would be better to load that one with the regular `require`.

**Comment by jonschlinkert** [comment]
I don't think it has anything to do with is-glob though. My guess is that `is-glob` just happens to be the first "lazy" property on `utils` that gets called, and it also happens to be a module dependency.

This is also an edge case. IMHO the `process.env` solution is looking like a great way to go, since it resolves this issue in a not-too-unusual way for the usage scenario without having to change the API or wrap code (this is not something that 99.999% of lazy-cache users will need to think about). 

I'd prefer if we could start with the `process.env` solution. it's simple and straightforward - and has the nice side benefit of solving any potential webpack transpiling issues (we've only had two or three lazy-cache related issues to date, and I think all of them had something to do with webpack). If we get feedback that this solution doesn't work for all use cases, or in an idiomatic way for certain cases, then we could revisit.  does that sound okay?

**Comment by es128** [comment]
It does sound fine, but I'm bringing up something that is tangential and you haven't quite addressed in your response. Is there any common usage of `minimatch` that does not involve `is-glob`? If not, what is gained by loading it lazily? 

In contrast, lazy loading makes total sense for all the other extensions that may or may not be used, and I have no concerns to raise with the solutions to this edge case that have been discussed.

**Comment by jonschlinkert** [comment]
wanted to mention first that I was completely wrong about the webpack stuff.  @doowb brought it up so I went and looked through their code and messed around with it a bit, it's not related in the slightest to this issue (or micromatch)

> I'm bringing up something that is tangential and you haven't quite addressed in your response. Is there any common usage of micromatch that does not involve is-glob

Probably not, and being a micro-lib it has a minute impact on init load times, we could probably go either way with it. I'm just a creature of habit and tend to like to follow the same pattern with all of the deps to keep my OCD at bay.

(tldr; feel free to ignore the rest, but in case you're interested in my reasoning.)

That said, this is missing the point of lazy-cache, which is to _only load micromatch and its dependencies when a method on micromatch is called_ (e.g. before even getting to is-glob), versus belching up the entire dependency tree regardless of whether or not a single method from our library is ever used (reminds me of how we use to load `kitchen-sync-with-extra-styles-just-in-case.js` onto every page in the browser, before intelligent loading, minification and so on).  

In reality, any particular example we focus on will probably represent some very small fraction of the init time in any given scenario, but the cumulative effect is surprising (if other nerds are interested in this stuff, I can post some before/after comparisons from libs that we've "lazied"). @doowb made this analogy recently: "You realize how little code you actually use from a lib when you try to get 100% coverage in unit tests". (maybe I should add a badge, like the code coverage ones: "100% lazy" jk)

I also completely get that init/load time is only up front, so the performance benefits are perhaps more transparent and useful in cases where applications are constantly re-initialized. But all applications would benefit, and the more we embrace the module pattern, the more this will be an area of opportunity for performance improvements.

**Comment by es128** [comment]
Yep I understand the problems with `require`'s slowness, and your reasoning does make sense.

But there are some cons to go with those pros. One, which this thread is all about, is a new opportunity for edge cases. But another that I'm not sure you've thought about, is that there may be cases - particularly in production environment - where deferring the module latency from startup to runtime may be much less desirable. There is the possibility of doing this at a particularly bad time in an application's lifecycle to be blocking the event loop, which would not be worth the tradeoff on better initialization time.

Just some food for thought. Robust opt-out options would be the solution in any case, which you're already working on.

**Comment by jonschlinkert** [comment]
> Robust opt-out options would be the solution in any case, which you're already working on.

I agree, this makes sense all around

> where deferring the module latency from startup to runtime may be much less desirable

IMHO this is a good example of why micro-libs are an ideal use case for lazy-caching. gotta run but these are good things to think about, thank you!

**Comment by jonschlinkert** [comment]
fixed by https://github.com/jonschlinkert/micromatch/commit/30655d15ee97161743e60c311482fcf92c9ddaec
